### ISSUE TITLE
Legge til express-samlebånd.

### ISSUE THREAD

**Issue by tta019** [inf112-v20/aerial-stingray#20]
Brukerhistorie: Som spiller trenger jeg at express-samlebånd fungerer som det skal for å kunne planlegge mine trekk.

Arbeidsoppgave: Legger til express-samlebånd på brettet i Tiled, og oppretter et eget object layer for express-samlebånd og gir den en type Express_Conveyor_<retning>, hvor retning er enten North, South, East, West, NorthWest, NorthSouth, NorthEast, SouthNorth, SouthEast, SouthWest,EastNorth, EastSouth, EastWest, WestNorth, WestSouth and EastWest. Denne typen kan hentes med map.getLayers().get(“OEvents”).getObjects() og vil ta en if-setning til å sjekke om tilen spillerens brikke står på faktisk er et express-samlebånd. Hvis sjekken returnerer true, vil brikken bevege seg 2 skritt i express-samlebåndets retning.

Akseptansekriterie: Hvis brikken står på et express-samlebånd så vil brikkens posisjon bli oppdatert 2 tiles etter hvilken retning express-samlebåndet går.

**Comment by danbojovic** [comment]
Known bug: Express_Conveyor_SouthWest case calls on Express_Conveyor_South case instead of its actual case, which is Express_Conveyor_SouthWest.
